### ISSUE TITLE
No permite desplazar verticalmente la lista de álbumes 

### ISSUE THREAD

**Issue by camilo-barreto-MISO** [ramirez-alejo/MISO-AppMoviles-Vinilos#51]
## Comportamiento esperado:
----
Al navegar a la pantalla de álbumes cuando se cargue la lista de álbumes debe permitir desplazar verticalmente 
## Comportamiento actual:
----
Cuando se navega a la pantalla de álbumes carga la lista de álbumes, pero no permite desplazar verticalmente  

## Pasos a reproducir
----
1.Ingresar al menú principal y hacer click en visitante
2. La aplicación navega a la pantalla de álbumes 
3. La aplicación carga la lista de álbumes 
4. Intentar desplazar verticalmente la lista 

## Evidencias
----

[Video evidencia PM2](https://drive.google.com/file/d/1z1MHFJamtwtzXgiQED3zMZKWLxF9SHGu/view?usp=drive_link)

## Contexto (Ambiente ejecución)
----
Emulador
Android 14.0 Upside Down Cake API level 34
Pixel_3a_API_34_extension_level_7_x86_64

## Información adicional
----

Sin información adicional

**Comment by augusto-romero-arango** [comment]
Se realiza la corrección de la navegación cambiando el tamaño del contenedor del lsitado de los álbumes para que no quedara por debajo de la barra inferior de navegación.

[Video de la corrección](https://uniandes-my.sharepoint.com/:v:/g/personal/a_romeroa23_uniandes_edu_co/EcQLOVHjnE9PgDp5TF9eKUUBTPsa3rCDWR4EX6CCxBFh_A?e=Zb7npz)
