### ISSUE TITLE
Pantalla de inicio no es fiel al diseño de figma

### ISSUE THREAD

**Issue by camilo-barreto-MISO** [ramirez-alejo/MISO-AppMoviles-Vinilos#52]
## Comportamiento esperado:
----
Al iniciar la aplicación la página de inicio debe ser fiel al diseño de figma 
## Comportamiento actual:
----
La página de inicio no es fiel al diseño de figma  

## Pasos a reproducir
----
1.Iniciar la aplicación 

## Evidencias
----

![image](https://github.com/ramirez-alejo/MISO-AppMoviles-Vinilos/assets/142703349/b77b5e7e-f8ad-4da5-85fd-28f7d16ceda1)

[Video evidencia PM1](https://drive.google.com/file/d/1hNdS8N-WG-S4FhKrQKc1i5tc_6hA52kG/view?usp=drive_link)

## Contexto (Ambiente ejecución)
----
Emulador
Android 14.0 Upside Down Cake API level 34
Pixel_3a_API_34_extension_level_7_x86_64

## Información adicional
----

Sin información adicional

**Comment by augusto-romero-arango** [comment]
Se hace la corrección de estilos de los typographies y espacios entre los diferentes títulos y botones.
![image](https://github.com/ramirez-alejo/MISO-AppMoviles-Vinilos/assets/142316821/e653ea58-7213-4350-b785-052364fb8150)
