### ISSUE TITLE
La lista de artistas no permite desplazar verticalmente 

### ISSUE THREAD

**Issue by camilo-barreto-MISO** [ramirez-alejo/MISO-AppMoviles-Vinilos#54]
## Comportamiento esperado:
----
Al navegar a la pantalla de artistas cuando se cargue la lista de artistas debe permitir desplazar verticalmente 
## Comportamiento actual:
----
Cuando se navega a la pantalla de artistas carga la lista de artistas, pero no permite desplazar verticalmente  

## Pasos a reproducir
----
1.Ingresar al menú principal y hacer click en visitante
2. La aplicación navega a la pantalla de álbumes 
3. La aplicación carga la lista de álbumes 
4. Hacer click en artistas en la barra de navegación 
5. La aplicación navega a la pantalla de artistas y carga la lista de artistas 
6. Intentar desplazar verticalmente la lista 

## Evidencias
----

[Video evidencia PM5](https://drive.google.com/file/d/1CUpCApnYN6SXy8rtxxvRRPI7wgWnI229/view?usp=drive_link)

## Contexto (Ambiente ejecución)
----
Emulador
Android 14.0 Upside Down Cake API level 34
Pixel_3a_API_34_extension_level_7_x86_64

## Información adicional
----

Sin información adicional

**Comment by augusto-romero-arango** [comment]
Se corrije el error. Ya permite desplazar el listado de artistas verticalmente

[Video con corrección](https://uniandes-my.sharepoint.com/:v:/g/personal/a_romeroa23_uniandes_edu_co/EWxPbUT2mKJFs8L5OgLJJowB-sW03Xxt2BqhKgnOXYt0xw?e=4wlQ41)
