### ISSUE TITLE
Barra de búsqueda de artistas no permite desplazar verticalmente

### ISSUE THREAD

**Issue by camilo-barreto-MISO** [ramirez-alejo/MISO-AppMoviles-Vinilos#55]
## Comportamiento esperado:
----
Al navegar a la pantalla de artistas cuando se hace click en la barra de búsqueda y se cargue la lista de artistas debe permitir desplazar verticalmente 
## Comportamiento actual:
----
Cuando se navega a la pantalla de artistas y se hace click en la barra de búsqueda carga la lista de artistas, pero no permite desplazar verticalmente  

## Pasos a reproducir
----
1.Ingresar al menú principal y hacer click en visitante
2. La aplicación navega a la pantalla de álbumes 
3. La aplicación carga la lista de álbumes 
4. Hacer click en artistas en la barra de navegación 
5. La aplicación navega a la pantalla de artistas y carga la lista de artistas 
6. Hacer click en la barra de busqueda 
7. Intentar desplazar verticalmente la lista 

## Evidencias
----

[Video evidencia PM6](https://drive.google.com/file/d/1PMGX2XmvtlooyBgnRLbah-WyTWC_bLx-/view?usp=drive_link)

## Contexto (Ambiente ejecución)
----
Emulador
Android 14.0 Upside Down Cake API level 34
Pixel_3a_API_34_extension_level_7_x86_64

## Información adicional
----

Sin información adicional

**Comment by augusto-romero-arango** [comment]
Se corrije el listado de artistas para que se pueda usar el scroll y no quede bloqueado por la barra de navegación inferior.

[Video con la corrección](https://uniandes-my.sharepoint.com/:v:/g/personal/a_romeroa23_uniandes_edu_co/EcQLOVHjnE9PgDp5TF9eKUUBTPsa3rCDWR4EX6CCxBFh_A?e=ynphdN)
